=== sbojanowski/plcda-kmcr/decor-core-runtime/DECOR-supported-datatypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="supportedDataTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dataType"/>
        <xs:element maxOccurs="unbounded" ref="atomicDataType"/>
        <xs:element maxOccurs="unbounded" ref="attribute"/>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataType">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="dataType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="desc" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="flavor"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
      </xs:sequence>
      <xs:attribute name="hasStrength" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:QName"/>
      <xs:attribute name="realm" type="xs:NCName"/>
      <xs:attribute name="represents"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="atomicDataType">
    <xs:complexType>
      <xs:choice minOccurs="0">
        <xs:element ref="atomicDataType" maxOccurs="unbounded"/>
        <xs:element ref="flavor" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="realm" type="xs:NCName"/>
      <xs:attribute name="represents"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="desc"/>
        <xs:choice>
          <xs:element ref="property"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="vocabulary"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="datatype" use="required" type="xs:NCName"/>
      <xs:attribute name="isOptional" use="required" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="value" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType>
      <xs:attribute name="minValue" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="vocabulary">
    <xs:complexType>
      <xs:attribute name="code" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="desc">
    <xs:complexType mixed="true">
      <xs:attribute name="language" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="flavor">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="desc"/>
        <xs:element minOccurs="0" ref="operationalization"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="flavor"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
      </xs:sequence>
      <xs:attribute name="hasStrength" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="realm" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="operationalization">
    <xs:complexType mixed="true">
      <xs:attribute name="language" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="element">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="desc" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      <xs:attribute name="conformance" use="required" type="xs:NCName"/>
      <xs:attribute name="datatype" use="optional" type="datatype"/>
      <xs:attribute name="isMandatory" use="required" type="xs:boolean"/>
      <xs:attribute name="maxOccurs" type="xs:NCName"/>
      <xs:attribute name="maximumMultiplicity"/>
      <xs:attribute name="minOccurs" type="xs:integer"/>
      <xs:attribute name="minimumMultiplicity" type="xs:integer"/>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="datatype">
     <xs:union memberTypes="xs:NCName xs:QName"/>
  </xs:simpleType>
</xs:schema>

=== sbojanowski/plcda-kmcr/decor-core-html/DECOR-supported-datatypes.xml
<!--
    DECOR-supported-datatypes
    Copyright (C) 2013-2016 Dr. Kai U. Heitmann, Alexander Henket

    List of supported data types in ART-DECOR

    reflects data types as <dataType> elements with the name
    name must be present (as of now) in coreschematrons directory as DTr1_{name}.sch

    data type elements are hierarchical representing inheritence, e.g.
    a SC is_a ST is_a ED is_a BIN

    Also reflects possibility of demotion

    <flavor> elements may be added as immediate child elements of a data type
    to reflect a data type flavor (variant, data type with further constraint),
    additionally shall carry a realm indicator, e.g. DE, NL, AT etc. or UV

    The mapping to one of the value domain data types of concepts in data sets
    is also shown.
    So far the possible mapping is shown for the following value domain data types
      blob boolean code complex date datetime decimal duration identifier ordinal
      quantity string text count

    kh 20130318 rev 20130325 20130910 20160517

-->
<?xml-model href="DECOR-supported-datatypes.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<supportedDataTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DECOR-supported-datatypes.xsd" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" type="hl7v3xml1">
    <dataType name="ANY" represents="blob boolean code complex date datetime decimal duration identifier ordinal quantity string text count">
        <desc language="en-US">ANY</desc>
        <dataType name="AD" represents="complex string text">
            <desc language="en-US">Address</desc>
            <flavor name="AD.PL" realm="PL">
                <desc language="pl-PL">Polski adres</desc>
                <element name="hl7:country" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:city" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:postalCode" minimumMultiplicity="0" maximumMultiplicity="1" conformance="O" isMandatory="false">
                    <attribute name="xsi:type" datatype="st" value="extPL:adxp.postalCode" isOptional="true"/>
                    <attribute name="postCity" datatype="st" isOptional="true"/>
                 </element>
                <element name="hl7:streetName" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:houseNumber" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:unitID" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:unitType" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:censusTract" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:streetAddressLine" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            </flavor>
            <flavor name="AD.PL.ORG" realm="PL">
                <desc language="pl-PL">Polski adres organizacji</desc>
                <element name="hl7:country" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:city" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:postalCode" minimumMultiplicity="0" maximumMultiplicity="1" conformance="O" isMandatory="false">
                    <attribute name="xsi:type" datatype="st" value="extPL:adxp.postalCode" isOptional="true"/>
                    <attribute name="postCity" datatype="st" isOptional="true"/>
                 </element>
                <element name="hl7:streetName" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:houseNumber" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:unitID" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:unitType" minimumMultiplicity="0" maximumMultiplicity="1" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:censusTract" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
                <element name="hl7:streetAddressLine" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            </flavor>
            <!-- official dtr1 attributes/elements -->
            <attribute name="use" isOptional="true" datatype="set_cs"/>
            <attribute name="isNotOrdered" isOptional="true" datatype="bl"/>
            <attribute name="nullFlavor" isOptional="true" datatype="cs"/>
            <element name="hl7:delimiter" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:country" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:state" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:county" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:city" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:postalCode" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:streetAddressLine" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:houseNumber" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:houseNumberNumeric" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:direction" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:streetName" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:streetNameBase" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:streetNameType" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:additionalLocator" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:unitID" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:unitType" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:careOf" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:censusTract" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryAddressLine" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryInstallationType" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryInstallationArea" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryInstallationQualifier" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryMode" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:deliveryModeIdentifier" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:buildingNumberSuffix" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:postBox" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
            <element name="hl7:precinct" minimumMultiplicity="0" maximumMultiplicity="*" datatype="ADXP" conformance="O" isMandatory="false"/>
        </dataType>
        <dataType name="BIN" represents="blob">
            <desc language="en-US">Binary Data</desc>
            <dataType name="ED" represents="text">
                <desc language="en-US">Encapsulated Data</desc>
                <dataType name="ST" represents="string">
                    <desc language="en-US">Character String</desc>
                    <dataType name="SC" represents="code">
                        <desc language="en-US">String with Codes</desc>
                        <attribute name="code" datatype="cs" isOptional="true"/>
                        <attribute name="codeSystem" datatype="oid" isOptional="true"/>
